export const USER_LIST_FAILED = 'USER_LIST_FAILED';
export const USER_LIST_LOADING = 'USER_LIST_LOADING';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DELETE_LOADING = 'USER_DELETE_LOADING';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_UPDATE_LOADING = 'USER_UPDATE_LOADING ';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
